version: '3.7'
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
     - mongodata:/data/db
    ports:
      - 27015:27017
    restart: unless-stopped
volumes:
  mongodata: